/* eslint-disable import/prefer-default-export */
export const toastSettings = {
    position: 'top-right',
    autoClose: 5000,
    hideProgressBar: false,
    closeOnClick: false,
    pauseOnHover: true,
    draggable: true,
    progress: undefined,
    theme: 'colored',
}

export const darkModeDefaultChartSettings = {
    timezone: 'Etc/UTC',
    priceScaleSelectionStrategyName: 'auto',
    dataWindowProperties: {
        background: 'rgba( 255, 254, 206, 0.2)',
        border: 'rgba( 96, 96, 144, 1)',
        font: 'Verdana',
        fontBold: false,
        fontItalic: false,
        fontSize: 10,
        transparency: 80,
        visible: true,
    },
    paneProperties: {
        backgroundType: 'solid',
        background: '#111721',
        backgroundGradientStartColor: '#111721',
        backgroundGradientEndColor: '#111721',
        vertGridProperties: {
            color: 'rgba(255, 255, 255, 0.15)',
            style: 0,
        },
        horzGridProperties: {
            color: 'rgba(255, 255, 255, 0.15)',
            style: 0,
        },
        crossHairProperties: {
            color: '#9598A1',
            style: 2,
            transparency: 0,
            width: 1,
        },
        topMargin: 10,
        bottomMargin: 8,
        axisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            isInverted: false,
        },
        legendProperties: {
            showStudyArguments: true,
            showStudyTitles: true,
            showStudyValues: true,
            showSeriesTitle: true,
            showSeriesOHLC: true,
            showLegend: true,
            showBarChange: true,
            showBackground: true,
            backgroundTransparency: 50,
            wrapText: false,
        },
    },
    scalesProperties: {
        backgroundColor: '#ffffff',
        lineColor: 'rgba(42, 46, 57, 0.14)',
        textColor: '#131722',
        fontSize: 12,
        scaleSeriesOnly: false,
        showSeriesLastValue: true,
        seriesLastValueMode: 1,
        showSeriesPrevCloseValue: false,
        showStudyLastValue: false,
        showSymbolLabels: false,
        showStudyPlotLabels: false,
        showBidAskLabels: false,
        showPrePostMarketPriceLabel: true,
        showFundamentalNameLabel: false,
        showFundamentalLastValue: false,
        barSpacing: 6,
        showCurrency: true,
        showUnit: true,
    },
    mainSeriesProperties: {
        style: 8,
        esdShowDividends: true,
        esdShowSplits: true,
        esdShowEarnings: true,
        esdShowBreaks: false,
        esdBreaksStyle: {
            color: 'rgba( 235, 77, 92, 1)',
            style: 2,
            width: 1,
        },
        esdFlagSize: 2,
        showCountdown: false,
        bidAsk: {
            visible: false,
            lineStyle: 1,
            lineWidth: 1,
            bidLineColor: '#2196F3',
            askLineColor: '#EF5350',
        },
        prePostMarket: {
            visible: true,
            lineStyle: 1,
            lineWidth: 1,
            preMarketColor: '#fb8c00',
            postMarketColor: '#2196f3',
        },
        highLowAvgPrice: {
            highLowPriceLinesVisible: false,
            highLowPriceLabelsVisible: false,
            averageClosePriceLineVisible: false,
            averageClosePriceLabelVisible: false,
        },
        showInDataWindow: true,
        visible: true,
        showPriceLine: true,
        priceLineWidth: 1,
        priceLineColor: '',
        baseLineColor: '#5d606b',
        showPrevClosePriceLine: false,
        prevClosePriceLineWidth: 1,
        prevClosePriceLineColor: 'rgba( 85, 85, 85, 1)',
        minTick: 'default',
        extendedHours: false,
        dividendsAdjustment: null,
        sessVis: false,
        statusViewStyle: {
            fontSize: 16,
            showExchange: true,
            showInterval: true,
            symbolTextSource: 'description',
        },
        candleStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            barColorsOnPrevClose: false,
            drawBody: true,
        },
        hollowCandleStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            drawBody: true,
        },
        haStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            showRealLastPrice: false,
            barColorsOnPrevClose: false,
            inputs: {},
            inputInfo: {},
            drawBody: true,
        },
        barStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            barColorsOnPrevClose: false,
            dontDrawOpen: false,
            thinBars: true,
        },
        hiloStyle: {
            color: '#2196f3',
            showBorders: true,
            borderColor: '#2196f3',
            showLabels: true,
            labelColor: '#2196f3',
            fontSize: 7,
            drawBody: true,
        },
        lineStyle: {
            color: '#2196f3',
            linestyle: 0,
            linewidth: 2,
            priceSource: 'close',
            styleType: 2,
        },
        areaStyle: {
            color1: 'rgba(33, 150, 243, 0.28)',
            color2: '#2196f3',
            linecolor: '#2196f3',
            linestyle: 0,
            linewidth: 2,
            priceSource: 'close',
            transparency: 100,
        },
        priceAxisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            isInverted: false,
            alignLabels: true,
        },
        renkoStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            borderUpColorProjection: '#336854',
            borderDownColorProjection: '#7f323f',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            inputs: {
                source: 'close',
                sources: 'Close',
                boxSize: 3,
                style: 'ATR',
                atrLength: 14,
                wicks: true,
            },
            inputInfo: {
                source: {
                    name: 'source',
                },
                sources: {
                    name: 'Source',
                },
                boxSize: {
                    name: 'Box size',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                wicks: {
                    name: 'Wicks',
                },
            },
        },
        pbStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            borderUpColorProjection: '#336854',
            borderDownColorProjection: '#7f323f',
            inputs: {
                source: 'close',
                lb: 3,
            },
            inputInfo: {
                source: {
                    name: 'Source',
                },
                lb: {
                    name: 'Number of line',
                },
            },
        },
        kagiStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                source: 'close',
                style: 'ATR',
                atrLength: 14,
                reversalAmount: 1,
            },
            inputInfo: {
                source: {
                    name: 'Source',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                reversalAmount: {
                    name: 'Reversal amount',
                },
            },
        },
        pnfStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                sources: 'Close',
                reversalAmount: 3,
                boxSize: 1,
                style: 'ATR',
                atrLength: 14,
                oneStepBackBuilding: false,
            },
            inputInfo: {
                sources: {
                    name: 'Source',
                },
                boxSize: {
                    name: 'Box size',
                },
                reversalAmount: {
                    name: 'Reversal amount',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                oneStepBackBuilding: {
                    name: 'One step back building',
                },
            },
        },
        baselineStyle: {
            baselineColor: 'rgba( 117, 134, 150, 1)',
            topFillColor1: 'rgba( 38, 166, 154, 0.28)',
            topFillColor2: 'rgba( 38, 166, 154, 0.05)',
            bottomFillColor1: 'rgba( 239, 83, 80, 0.05)',
            bottomFillColor2: 'rgba( 239, 83, 80, 0.28)',
            topLineColor: 'rgba( 38, 166, 154, 1)',
            bottomLineColor: 'rgba( 239, 83, 80, 1)',
            topLineWidth: 2,
            bottomLineWidth: 2,
            priceSource: 'close',
            transparency: 50,
            baseLevelPercentage: 50,
        },
        rangeStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            thinBars: true,
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                range: 10,
                phantomBars: false,
            },
            inputInfo: {
                range: {
                    name: 'Range',
                },
                phantomBars: {
                    name: 'Phantom bars',
                },
            },
        },
        symbol: 'CAKE/BNB',
        shortName: '',
        timeframe: '',
        onWidget: false,
        interval: '720',
        unitId: null,
        currencyId: null,
    },
    chartEventsSourceProperties: {
        visible: true,
        futureOnly: true,
        breaks: {
            color: 'rgba(85, 85, 85, 1)',
            visible: false,
            style: 2,
            width: 1,
        },
    },
    tradingProperties: {
        showPositions: true,
        showOrders: true,
        showExecutions: true,
        extendLeft: true,
        lineLength: 5,
        lineWidth: 1,
        lineStyle: 0,
    },
    editorFontsList: {
        0: 'Verdana',
        1: 'Courier New',
        2: 'Times New Roman',
        3: 'Arial',
    },
    volumePaneSize: 'large',
}

export const lightModeDefaultChartSettings = {
    timezone: 'Etc/UTC',
    priceScaleSelectionStrategyName: 'auto',
    dataWindowProperties: {
        background: 'rgba( 255, 254, 206, 0.2)',
        border: 'rgba( 96, 96, 144, 1)',
        font: 'Verdana',
        fontBold: false,
        fontItalic: false,
        fontSize: 10,
        transparency: 80,
        visible: true,
    },
    paneProperties: {
        backgroundType: 'solid',
        background: '#F8F7FC',
        backgroundGradientStartColor: '#F8F7FC',
        backgroundGradientEndColor: '#F8F7FC',
        vertGridProperties: {
            color: 'rgba(42, 46, 57, 0.06)',
            style: 0,
        },
        horzGridProperties: {
            color: 'rgba(42, 46, 57, 0.06)',
            style: 0,
        },
        crossHairProperties: {
            color: '#9598A1',
            style: 2,
            transparency: 0,
            width: 1,
        },
        topMargin: 10,
        bottomMargin: 8,
        axisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            isInverted: false,
        },
        legendProperties: {
            showStudyArguments: true,
            showStudyTitles: true,
            showStudyValues: true,
            showSeriesTitle: true,
            showSeriesOHLC: true,
            showLegend: true,
            showBarChange: true,
            showBackground: true,
            backgroundTransparency: 50,
            wrapText: false,
        },
    },
    scalesProperties: {
        backgroundColor: '#ffffff',
        lineColor: 'rgba(42, 46, 57, 0.14)',
        textColor: '#131722',
        fontSize: 12,
        scaleSeriesOnly: false,
        showSeriesLastValue: true,
        seriesLastValueMode: 1,
        showSeriesPrevCloseValue: false,
        showStudyLastValue: false,
        showSymbolLabels: false,
        showStudyPlotLabels: false,
        showBidAskLabels: false,
        showPrePostMarketPriceLabel: true,
        showFundamentalNameLabel: false,
        showFundamentalLastValue: false,
        barSpacing: 6,
        showCurrency: true,
        showUnit: true,
    },
    mainSeriesProperties: {
        style: 8,
        esdShowDividends: true,
        esdShowSplits: true,
        esdShowEarnings: true,
        esdShowBreaks: false,
        esdBreaksStyle: {
            color: 'rgba( 235, 77, 92, 1)',
            style: 2,
            width: 1,
        },
        esdFlagSize: 2,
        showCountdown: false,
        bidAsk: {
            visible: false,
            lineStyle: 1,
            lineWidth: 1,
            bidLineColor: '#2196F3',
            askLineColor: '#EF5350',
        },
        prePostMarket: {
            visible: true,
            lineStyle: 1,
            lineWidth: 1,
            preMarketColor: '#fb8c00',
            postMarketColor: '#2196f3',
        },
        highLowAvgPrice: {
            highLowPriceLinesVisible: false,
            highLowPriceLabelsVisible: false,
            averageClosePriceLineVisible: false,
            averageClosePriceLabelVisible: false,
        },
        showInDataWindow: true,
        visible: true,
        showPriceLine: true,
        priceLineWidth: 1,
        priceLineColor: '',
        baseLineColor: '#5d606b',
        showPrevClosePriceLine: false,
        prevClosePriceLineWidth: 1,
        prevClosePriceLineColor: 'rgba( 85, 85, 85, 1)',
        minTick: 'default',
        extendedHours: false,
        dividendsAdjustment: null,
        sessVis: false,
        statusViewStyle: {
            fontSize: 16,
            showExchange: true,
            showInterval: true,
            symbolTextSource: 'description',
        },
        candleStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            barColorsOnPrevClose: false,
            drawBody: true,
        },
        hollowCandleStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            drawBody: true,
        },
        haStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            showRealLastPrice: false,
            barColorsOnPrevClose: false,
            inputs: {},
            inputInfo: {},
            drawBody: true,
        },
        barStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            barColorsOnPrevClose: false,
            dontDrawOpen: false,
            thinBars: true,
        },
        hiloStyle: {
            color: '#2196f3',
            showBorders: true,
            borderColor: '#2196f3',
            showLabels: true,
            labelColor: '#2196f3',
            fontSize: 7,
            drawBody: true,
        },
        lineStyle: {
            color: '#2196f3',
            linestyle: 0,
            linewidth: 2,
            priceSource: 'close',
            styleType: 2,
        },
        areaStyle: {
            color1: 'rgba(33, 150, 243, 0.28)',
            color2: '#2196f3',
            linecolor: '#2196f3',
            linestyle: 0,
            linewidth: 2,
            priceSource: 'close',
            transparency: 100,
        },
        priceAxisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            isInverted: false,
            alignLabels: true,
        },
        renkoStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            borderUpColorProjection: '#336854',
            borderDownColorProjection: '#7f323f',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            inputs: {
                source: 'close',
                sources: 'Close',
                boxSize: 3,
                style: 'ATR',
                atrLength: 14,
                wicks: true,
            },
            inputInfo: {
                source: {
                    name: 'source',
                },
                sources: {
                    name: 'Source',
                },
                boxSize: {
                    name: 'Box size',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                wicks: {
                    name: 'Wicks',
                },
            },
        },
        pbStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            borderUpColorProjection: '#336854',
            borderDownColorProjection: '#7f323f',
            inputs: {
                source: 'close',
                lb: 3,
            },
            inputInfo: {
                source: {
                    name: 'Source',
                },
                lb: {
                    name: 'Number of line',
                },
            },
        },
        kagiStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                source: 'close',
                style: 'ATR',
                atrLength: 14,
                reversalAmount: 1,
            },
            inputInfo: {
                source: {
                    name: 'Source',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                reversalAmount: {
                    name: 'Reversal amount',
                },
            },
        },
        pnfStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                sources: 'Close',
                reversalAmount: 3,
                boxSize: 1,
                style: 'ATR',
                atrLength: 14,
                oneStepBackBuilding: false,
            },
            inputInfo: {
                sources: {
                    name: 'Source',
                },
                boxSize: {
                    name: 'Box size',
                },
                reversalAmount: {
                    name: 'Reversal amount',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                oneStepBackBuilding: {
                    name: 'One step back building',
                },
            },
        },
        baselineStyle: {
            baselineColor: 'rgba( 117, 134, 150, 1)',
            topFillColor1: 'rgba( 38, 166, 154, 0.28)',
            topFillColor2: 'rgba( 38, 166, 154, 0.05)',
            bottomFillColor1: 'rgba( 239, 83, 80, 0.05)',
            bottomFillColor2: 'rgba( 239, 83, 80, 0.28)',
            topLineColor: 'rgba( 38, 166, 154, 1)',
            bottomLineColor: 'rgba( 239, 83, 80, 1)',
            topLineWidth: 2,
            bottomLineWidth: 2,
            priceSource: 'close',
            transparency: 50,
            baseLevelPercentage: 50,
        },
        rangeStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            thinBars: true,
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                range: 10,
                phantomBars: false,
            },
            inputInfo: {
                range: {
                    name: 'Range',
                },
                phantomBars: {
                    name: 'Phantom bars',
                },
            },
        },
        symbol: 'CAKE/BNB',
        shortName: '',
        timeframe: '',
        onWidget: false,
        interval: '720',
        unitId: null,
        currencyId: null,
    },
    chartEventsSourceProperties: {
        visible: true,
        futureOnly: true,
        breaks: {
            color: 'rgba(85, 85, 85, 1)',
            visible: false,
            style: 2,
            width: 1,
        },
    },
    tradingProperties: {
        showPositions: true,
        showOrders: true,
        showExecutions: true,
        extendLeft: true,
        lineLength: 5,
        lineWidth: 1,
        lineStyle: 0,
    },
    editorFontsList: {
        0: 'Verdana',
        1: 'Courier New',
        2: 'Times New Roman',
        3: 'Arial',
    },
    volumePaneSize: 'large',
}

export const utopiaDefaultChartSettings = {
    timezone: 'Etc/UTC',
    priceScaleSelectionStrategyName: 'auto',
    dataWindowProperties: {
        background: 'rgba( 255, 254, 206, 0.2)',
        border: 'rgba( 96, 96, 144, 1)',
        font: 'Verdana',
        fontBold: false,
        fontItalic: false,
        fontSize: 10,
        transparency: 80,
        visible: true,
    },
    paneProperties: {
        backgroundType: 'solid',
        background: '#150035',
        backgroundGradientStartColor: '#150035',
        backgroundGradientEndColor: '#150035',
        vertGridProperties: {
            color: 'rgba(255, 255, 255, 0.07)',
            style: 0,
        },
        horzGridProperties: {
            color: 'rgba(255, 255, 255, 0.07)',
            style: 0,
        },
        crossHairProperties: {
            color: '#9598A1',
            style: 2,
            transparency: 0,
            width: 1,
        },
        topMargin: 10,
        bottomMargin: 8,
        axisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            alignLabels: true,
            isInverted: false,
        },
        legendProperties: {
            showStudyArguments: true,
            showStudyTitles: true,
            showStudyValues: true,
            showSeriesTitle: true,
            showSeriesOHLC: true,
            showLegend: true,
            showBarChange: true,
            showBackground: true,
            backgroundTransparency: 50,
            wrapText: false,
        },
    },
    scalesProperties: {
        backgroundColor: '#ffffff',
        lineColor: 'rgba(42, 46, 57, 0.14)',
        textColor: 'rgba(178, 181, 190, 1)',
        fontSize: 12,
        scaleSeriesOnly: false,
        showSeriesLastValue: true,
        seriesLastValueMode: 1,
        showSeriesPrevCloseValue: false,
        showStudyLastValue: false,
        showSymbolLabels: false,
        showStudyPlotLabels: false,
        showBidAskLabels: false,
        showPrePostMarketPriceLabel: true,
        showFundamentalNameLabel: false,
        showFundamentalLastValue: false,
        barSpacing: 6,
        showCurrency: true,
        showUnit: true,
    },
    mainSeriesProperties: {
        style: 8,
        esdShowDividends: true,
        esdShowSplits: true,
        esdShowEarnings: true,
        esdShowBreaks: false,
        esdBreaksStyle: {
            color: 'rgba( 235, 77, 92, 1)',
            style: 2,
            width: 1,
        },
        esdFlagSize: 2,
        showCountdown: false,
        bidAsk: {
            visible: false,
            lineStyle: 1,
            lineWidth: 1,
            bidLineColor: '#2196F3',
            askLineColor: '#EF5350',
        },
        prePostMarket: {
            visible: true,
            lineStyle: 1,
            lineWidth: 1,
            preMarketColor: '#fb8c00',
            postMarketColor: '#2196f3',
        },
        highLowAvgPrice: {
            highLowPriceLinesVisible: false,
            highLowPriceLabelsVisible: false,
            averageClosePriceLineVisible: false,
            averageClosePriceLabelVisible: false,
        },
        showInDataWindow: true,
        visible: true,
        showPriceLine: true,
        priceLineWidth: 1,
        priceLineColor: '',
        baseLineColor: '#5d606b',
        showPrevClosePriceLine: false,
        prevClosePriceLineWidth: 1,
        prevClosePriceLineColor: 'rgba( 85, 85, 85, 1)',
        minTick: 'default',
        extendedHours: false,
        dividendsAdjustment: null,
        sessVis: false,
        statusViewStyle: {
            fontSize: 16,
            showExchange: true,
            showInterval: true,
            symbolTextSource: 'description',
        },
        candleStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            barColorsOnPrevClose: false,
            drawBody: true,
        },
        hollowCandleStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            drawBody: true,
        },
        haStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            drawWick: true,
            drawBorder: true,
            borderColor: '#378658',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            wickColor: '#B5B5B8',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            showRealLastPrice: false,
            barColorsOnPrevClose: false,
            inputs: {},
            inputInfo: {},
            drawBody: true,
        },
        barStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            barColorsOnPrevClose: false,
            dontDrawOpen: false,
            thinBars: true,
        },
        hiloStyle: {
            color: '#2196f3',
            showBorders: true,
            borderColor: '#2196f3',
            showLabels: true,
            labelColor: '#2196f3',
            fontSize: 7,
            drawBody: true,
        },
        lineStyle: {
            color: '#2196f3',
            linestyle: 0,
            linewidth: 2,
            priceSource: 'close',
            styleType: 2,
        },
        areaStyle: {
            color1: 'rgba(33, 150, 243, 0.28)',
            color2: '#2196f3',
            linecolor: '#2196f3',
            linestyle: 0,
            linewidth: 2,
            priceSource: 'close',
            transparency: 100,
        },
        priceAxisProperties: {
            autoScale: true,
            autoScaleDisabled: false,
            lockScale: false,
            percentage: false,
            percentageDisabled: false,
            indexedTo100: false,
            log: false,
            logDisabled: false,
            isInverted: false,
            alignLabels: true,
        },
        renkoStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            borderUpColorProjection: '#336854',
            borderDownColorProjection: '#7f323f',
            wickUpColor: '#26a69a',
            wickDownColor: '#ef5350',
            inputs: {
                source: 'close',
                sources: 'Close',
                boxSize: 3,
                style: 'ATR',
                atrLength: 14,
                wicks: true,
            },
            inputInfo: {
                source: {
                    name: 'source',
                },
                sources: {
                    name: 'Source',
                },
                boxSize: {
                    name: 'Box size',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                wicks: {
                    name: 'Wicks',
                },
            },
        },
        pbStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            borderUpColor: '#26a69a',
            borderDownColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            borderUpColorProjection: '#336854',
            borderDownColorProjection: '#7f323f',
            inputs: {
                source: 'close',
                lb: 3,
            },
            inputInfo: {
                source: {
                    name: 'Source',
                },
                lb: {
                    name: 'Number of line',
                },
            },
        },
        kagiStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                source: 'close',
                style: 'ATR',
                atrLength: 14,
                reversalAmount: 1,
            },
            inputInfo: {
                source: {
                    name: 'Source',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                reversalAmount: {
                    name: 'Reversal amount',
                },
            },
        },
        pnfStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                sources: 'Close',
                reversalAmount: 3,
                boxSize: 1,
                style: 'ATR',
                atrLength: 14,
                oneStepBackBuilding: false,
            },
            inputInfo: {
                sources: {
                    name: 'Source',
                },
                boxSize: {
                    name: 'Box size',
                },
                reversalAmount: {
                    name: 'Reversal amount',
                },
                style: {
                    name: 'Style',
                },
                atrLength: {
                    name: 'ATR length',
                },
                oneStepBackBuilding: {
                    name: 'One step back building',
                },
            },
        },
        baselineStyle: {
            baselineColor: 'rgba( 117, 134, 150, 1)',
            topFillColor1: 'rgba( 38, 166, 154, 0.28)',
            topFillColor2: 'rgba( 38, 166, 154, 0.05)',
            bottomFillColor1: 'rgba( 239, 83, 80, 0.05)',
            bottomFillColor2: 'rgba( 239, 83, 80, 0.28)',
            topLineColor: 'rgba( 38, 166, 154, 1)',
            bottomLineColor: 'rgba( 239, 83, 80, 1)',
            topLineWidth: 2,
            bottomLineWidth: 2,
            priceSource: 'close',
            transparency: 50,
            baseLevelPercentage: 50,
        },
        rangeStyle: {
            upColor: '#26a69a',
            downColor: '#ef5350',
            thinBars: true,
            upColorProjection: '#336854',
            downColorProjection: '#7f323f',
            inputs: {
                range: 10,
                phantomBars: false,
            },
            inputInfo: {
                range: {
                    name: 'Range',
                },
                phantomBars: {
                    name: 'Phantom bars',
                },
            },
        },
        symbol: 'CAKE/BNB',
        shortName: '',
        timeframe: '',
        onWidget: false,
        interval: '720',
        unitId: null,
        currencyId: null,
    },
    chartEventsSourceProperties: {
        visible: true,
        futureOnly: true,
        breaks: {
            color: 'rgba(85, 85, 85, 1)',
            visible: false,
            style: 2,
            width: 1,
        },
    },
    tradingProperties: {
        showPositions: true,
        showOrders: true,
        showExecutions: true,
        extendLeft: true,
        lineLength: 5,
        lineWidth: 1,
        lineStyle: 0,
    },
    editorFontsList: {
        0: 'Verdana',
        1: 'Courier New',
        2: 'Times New Roman',
        3: 'Arial',
    },
    volumePaneSize: 'large',
}
